services:
  pg_normalized:
    build: services/pg_normalized
    volumes:
      - ./:/tmp/db
      - pg_normalized:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 10083:5432

  web:
    build: services/web
    depends_on:
      - pg_normalized
    ports:
      - 10084:8000
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=pass
      - PG_HOST=pg_normalized
      - PG_PORT=5432
    volumes:
      - ./services/web:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 1084:80
    depends_on:
      - web

volumes:
  pg_normalized:
  static_volume:
  media_volume:
